### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by PierreLeGuen** [devs-group/gatsby-source-medium-feed#1]
Hello, just tried to install your plugin and this error happens at the beginning of the install :

```bash
$ npm i -S gatsby-plugin-medium-feed 
npm ERR! Linux 4.4.0-17763-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-S" "gatsby-plugin-medium-feed" 
npm ERR! node v8.10.0 
npm ERR! npm  v3.5.2

npm ERR! Cannot convert undefined or null to object 
npm ERR!  
npm ERR! If you need help, you may report this error at: 
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request: 
npm ERR!     ../npm-debug.log
```

**Comment by PierreLeGuen** [comment]
Here is the full log :
`$ cat ../npm-debug.log 
`

```bash
0 info it worked if it ends with ok 
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-S',
1 verbose cli   'gatsby-plugin-medium-feed' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting 
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gatsby-plugin-medium-feed
8 silly fetchNamedPackageData gatsby-plugin-medium-feed
9 silly mapToRegistry name gatsby-plugin-medium-feed
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/gatsby-plugin-medium-feed
13 verbose request uri https://registry.npmjs.org/gatsby-plugin-medium-feed
14 verbose request no auth needed
15 info attempt registry request try #1 at 8:10:42 AM
16 verbose request id b4d3ed26b37594d4 
17 verbose etag W/"416eda813bd415b94a7f951eae84b1ff"
18 verbose lastModified Wed, 01 May 2019 18:39:02 GMT
19 http request GET https://registry.npmjs.org/gatsby-plugin-medium-feed
20 http 304 https://registry.npmjs.org/gatsby-plugin-medium-feed
21 verbose headers { date: 'Thu, 20 Jun 2019 07:10:46 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'set-cookie':
21 verbose headers    [ '__cfduid=deacb9dc68dab13ae74811a88e49238b21561014645; expires=Fri, 19-Jun-20 07:10:45 GMT; path=/; domain=.npmjs.org; HttpOnly' ],
21 verbose headers   'cf-cache-status': 'REVALIDATED',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   'cf-ray': '4e9becbed959a85b-CDG',
21 verbose headers   etag: '"416eda813bd415b94a7f951eae84b1ff"',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   'last-modified': 'Wed, 01 May 2019 18:39:02 GMT',
21 verbose headers   vary: 'accept-encoding, accept',
21 verbose headers   'x-amz-meta-rev': '4-fd4f0e4a140f431a78deff115202db1a',
21 verbose headers   server: 'cloudflare' } 
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 20 Jun 2019 07:10:46 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'set-cookie':
22 silly get      [ '__cfduid=deacb9dc68dab13ae74811a88e49238b21561014645; expires=Fri, 19-Jun-20 07:10:45 GMT; path=/; domain=.npmjs.org; HttpOnly' ],
22 silly get     'cf-cache-status': 'REVALIDATED', 
22 silly get     'cache-control': 'max-age=300',
22 silly get     'cf-ray': '4e9becbed959a85b-CDG',
22 silly get     etag: '"416eda813bd415b94a7f951eae84b1ff"', 
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     'last-modified': 'Wed, 01 May 2019 18:39:02 GMT',
22 silly get     vary: 'accept-encoding, accept',
22 silly get     'x-amz-meta-rev': '4-fd4f0e4a140f431a78deff115202db1a',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/gatsby-plugin-medium-feed from cache
24 verbose get saving gatsby-plugin-medium-feed to /home/pleguen/.npm/registry.npmjs.org/gatsby-plugin-medium-feed/.cache.json
25 verbose stack TypeError: Cannot convert undefined or null to object
25 verbose stack     at Function.keys (<anonymous>)
25 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:121:29)
25 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50 
25 verbose stack     at /usr/share/npm/lib/utils/pulse-till-done.js:19:8
25 verbose stack     at saved (/usr/share/npm/lib/cache/caching-client.js:168:7)
25 verbose stack     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:210:7
25 verbose stack     at FSReqWrap.oncomplete (fs.js:135:15)
26 verbose cwd /mnt/c/Users/pleguen/Documents/git/myprojects/gatsby-starter-lumen
27 error Linux 4.4.0-17763-Microsoft
28 error argv "/usr/bin/node" "/usr/bin/npm" "i" "-S" "gatsby-plugin-medium-feed" 
29 error node v8.10.0
30 error npm  v3.5.2
31 error Cannot convert undefined or null to object
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues> 
33 verbose exit [ 1, true ]
```

**Comment by segidev** [comment]
Thank your for the report. Did it work meanwhile?

**Comment by drodil** [comment]
It's actually wrongly named in the README; it's gatsby-source-medium-feed and NOT gatsby-plugin-medium-feed

**Comment by segidev** [comment]
We merged the pull requests for the readme. I wil close this issue since we are no longer getting feedback about the bug.

Thank you
